src/Himall.Web/Areas/Admin/Controllers/ShopBonusController.cs
using Himall.CommonModel;
using Himall.IServices;
using Himall.DTO.QueryModel;
using Himall.Model;
using Himall.Web.Framework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Himall.Web.Areas.Admin.Controllers
{
    [MarketingAuthorization]
    public class ShopBonusController : BaseAdminController
    {
        private IMarketService _iMarketService;

        public ShopBonusController(IMarketService iMarketService)
        {
            _iMarketService = iMarketService;
        }
        //
        // GET: /Admin/ShopBonus/
        public ActionResult Management()
        {
            return View();
        }

        public ActionResult ServiceSetting()
        {
            MarketSettingInfo model = _iMarketService.GetServiceSetting( MarketType.RandomlyBonus );
            return View( model );
        }

        [HttpPost]
        [UnAuthorize]
        public ActionResult SaveServiceSetting( decimal Price )
        {
            Result result = new Result();
            var model = new MarketSettingInfo { Price = Price , TypeId = MarketType.RandomlyBonus };
            _iMarketService.AddOrUpdateServiceSetting( model );
            result.success = true;
            result.msg = "保存成功！";
            return Json( result );
        }

        [UnAuthorize]
        public ActionResult List( string shopName , int page , int rows )
        {
            var queryModel = new MarketBoughtQuery()
            {
                PageSize = rows ,
                PageNo = page ,
                ShopName = shopName ,
                MarketType = MarketType.RandomlyBonus
            };
            QueryPageModel<MarketServiceRecordInfo> marketEntities = _iMarketService.GetBoughtShopList( queryModel );

            var market = marketEntities.Models.OrderByDescending( m => m.MarketServiceId ).ThenByDescending( m => m.EndTime ).ToArray().Select( item => new
            {
                Id = item.Id ,
                StartDate = item.StartTime.ToString( "yyyy-MM-dd" ) ,
                EndDate = item.EndTime.ToString( "yyyy-MM-dd" ) ,
                ShopName = item.ActiveMarketServiceInfo.ShopName
            } );

            return Json( new { rows = market , total = marketEntities.Total } );
        }
	}
}

src/Himall.Web/Areas/Mobile/Controllers/ShopBonusController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Web;
using System.Web.Mvc;
using Himall.Core;
using Himall.IServices;
using Himall.Model;
using Himall.Web.App_Code.Common;
using Himall.Web.Areas.Mobile.Models;
using Himall.Web.Areas.SellerAdmin.Models;
using Himall.Web.Framework;
using Senparc.Weixin.MP.AdvancedAPIs.OAuth;
using Senparc.Weixin.MP.AdvancedAPIs.User;
using Senparc.Weixin.MP.CommonAPIs;
using Senparc.Weixin.MP.Helpers;
using Himall.DTO;

namespace Himall.Web.Areas.Mobile.Controllers
{
    public class ShopBonusController : BaseMobileTemplatesController
    {
        private IShopBonusService _bonusService = null;
        private SiteSettingsInfo _siteSetting = null;
        private IWXCardService _iWXCardService = null;
        private IVShopService _iVShopService;
        private IShopService _iShopService;
        private WXCardLogInfo.CouponTypeEnum ThisCouponType = WXCardLogInfo.CouponTypeEnum.Bonus;
        public ShopBonusController(IShopBonusService iShopBonusService,
            IWXCardService iWXCardService,
            IVShopService iVShopService,
            IShopService iShopService
            )
        {
            this._siteSetting = CurrentSiteSetting;
            if (string.IsNullOrWhiteSpace(this._siteSetting.WeixinAppId) || string.IsNullOrWhiteSpace(this._siteSetting.WeixinAppSecret))
            {
                throw new HimallException("未配置公众号参数");
            }
            this._bonusService = iShopBonusService;
            this._iWXCardService = iWXCardService;
            _iVShopService = iVShopService;
            _iShopService = iShopService;
        }


        public ActionResult Index(long id)
        {
            if (this.PlatformType != Core.PlatformType.WeiXin)
            {
                Log.Info(this.PlatformType.ToString());
                return Content("只能在微信端访问");
            }

            var bonus = this._bonusService.GetByGrantId(id);
            if (bonus == null)
            {
                Log.Info("红包失踪，id = " + id);
                return Redirect("/m-weixin/ShopBonus/Invalidtwo");
            }

            //授权获取openid相关
            string code = HttpContext.Request["code"];
            OAuthAccessTokenResult wxOpenInfo = null;
            if (string.IsNullOrEmpty(code))
            {
                string selfAddress = Request.Url.ToString();
                string url = OAuthApi.GetAuthorizeUrl(this._siteSetting.WeixinAppId.Trim(), selfAddress, "STATE", Senparc.Weixin.MP.OAuthScope.snsapi_userinfo, "code");
                return Redirect(url);
            }
            else
            {
                try
                {
                    wxOpenInfo = OAuthApi.GetAccessToken(this._siteSetting.WeixinAppId.Trim(), this._siteSetting.WeixinAppSecret.Trim(), code, "authorization_code");
                }
                catch (Exception e)
                {
                    Exception innerEx = e.InnerException == null ? e : e.InnerException;
                    return Content(innerEx.Message);
                }
            }

            OAuthUserInfo wxUserInfo = OAuthApi.GetUserInfo(wxOpenInfo.access_token, wxOpenInfo.openid);
            ShopBonusModel model = new ShopBonusModel(bonus);
            if (model.DateEnd <= DateTime.Now || model.IsInvalid || model.BonusDateEnd <= DateTime.Now)  //过期、失效
            {
                return Redirect("/m-weixin/ShopBonus/Expired/" + model.Id + "?openId=" + wxOpenInfo.openid + "&grantid=" + id + "&wxhead=" + wxUserInfo.headimgurl);
            }
            else if (model.DateStart > DateTime.Now) // 未开始
            {
                return Redirect("/m-weixin/ShopBonus/NotStart/" + model.Id);
            }
            ShopReceiveModel obj = (ShopReceiveModel)this._bonusService.Receive(id, wxUserInfo.openid, wxUserInfo.headimgurl, wxUserInfo.nickname);

            //防两次刷新
            string cacheDName = "WXSB_U" + wxOpenInfo.openid + "_D" + id.ToString();
            if (obj.State == ShopReceiveStatus.Receive)
            {
                var _tmp = Cache.Get<ShopReceiveModel>(cacheDName);
                if (_tmp != null && _tmp.State == ShopReceiveStatus.CanReceive)
                {
                    obj = _tmp;
                }
            }

            var host = CurrentUrlHelper.CurrentUrl();
            if (obj.State == ShopReceiveStatus.CanReceive)
            {
                Cache.Insert<ShopReceiveModel>(cacheDName, obj, 2);
                return Redirect("/m-weixin/ShopBonus/Completed/" + model.Id + "?openId=" + wxUserInfo.openid + "&price=" + obj.Price + "&user=" + obj.UserName + "&grantid=" + id + "&rid=" + obj.Id + "&wxhead=" + wxUserInfo.headimgurl + "&host=" + host);
            }
            else if (obj.State == ShopReceiveStatus.CanReceiveNotUser)
            {
                return Redirect("/m-weixin/ShopBonus/CompletedNotUser/" + model.Id + "?openId=" + wxUserInfo.openid + "&price=" + obj.Price + "&grantid=" + id + "&rid=" + obj.Id + "&wxhead=" + wxUserInfo.headimgurl + "&host=" + host);
            }
            else if (obj.State == ShopReceiveStatus.Receive)
            {
                return Redirect("/m-weixin/ShopBonus/HasReceive/" + model.Id + "?openId=" + wxUserInfo.openid + "&grantid=" + id + "&wxhead=" + wxUserInfo.headimgurl + "&host=" + host);
            }
            else if (obj.State == ShopReceiveStatus.HaveNot)
            {
                return Redirect("/m-weixin/ShopBonus/HaveNot/" + model.Id + "?openId=" + wxUserInfo.openid + "&grantid=" + id + "&wxhead=" + wxUserInfo.headimgurl);
            }
            else if (obj.State == ShopReceiveStatus.Invalid)
            {
                return Redirect("/m-weixin/ShopBonus/Expired/" + model.Id + "?openId=" + wxUserInfo.openid + "&grantid=" + id + "&wxhead=" + wxUserInfo.headimgurl);
            }
            else
            {
                throw new Exception("领取发生异常");
            }
        }

        /// <summary>
        /// 取微信同步卡券信息
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult GetWXCardData(long id, long rid)
        {
            WXJSCardModel result = new WXJSCardModel();
            bool isdataok = true;
            #region 同步微信前信息准备
            if (isdataok)
            {
                if (this.PlatformType == PlatformType.WeiXin)
                {
                    result = _iWXCardService.GetJSWeiXinCard(id, rid, ThisCouponType);
                }
            }
            #endregion
            return Json<dynamic>(success: true, data: result);
        }

        public ActionResult Completed(long id, string openId = "", decimal price = 0, string user = "", long grantid = 0, long rid = 0, string wxhead = "", string host = "")
        {
            host = CurrentUrlHelper.CurrentUrl();
            ShopBonusDataModel dataModel = new ShopBonusDataModel();
            ShopBonusModel model = new ShopBonusModel(this._bonusService.Get(id));
            dataModel.GrantId = grantid;
            dataModel.ShareHref = host + "/m-weixin/shopbonus/index/" + grantid.ToString();
            dataModel.HeadImg = wxhead;
            //dataModel.HeadImg = Himall.Core.HimallIO.GetImagePath(dataModel.HeadImg);
            dataModel.ShopAddress = GetShopAddress(model.ShopId);
            dataModel.UserName = user;
            dataModel.Price = price;
            dataModel.OpenId = openId;
            dataModel.ShopName = Application.ShopApplication.GetShopName(model.ShopId);
            ViewBag.DataModel = dataModel;
            model.ShareImg = HimallIO.GetRomoteImagePath(model.ShareImg);
            if (!string.IsNullOrWhiteSpace(model.ShareImg))
            {
                if (model.ShareImg.Substring(0, 4) != "http")
                {
                    model.ShareImg = host + model.ShareImg;
                }
            }
            model.ReceiveId = rid;

            #region 同步微信前信息准备
            if (model.SynchronizeCard == true && this.PlatformType == PlatformType.WeiXin)
            {
                model.WXJSInfo = _iWXCardService.GetSyncWeiXin(id, rid, ThisCouponType, Request.Url.AbsoluteUri);
                if (model.WXJSInfo != null)
                {
                    model.IsShowSyncWeiXin = true;
                    //model.WXJSCardInfo = ser_wxcard.GetJSWeiXinCard(id, rid, ThisCouponType);    //同步方式有重复留的Bug
                }
            }
            #endregion

            return View(model);
        }

        public ActionResult CompletedNotUser(long id, long rid, string openId = "", decimal price = 0, long grantid = 0, string wxhead = "", string host = "")
        {
            host = CurrentUrlHelper.CurrentUrl();
            ShopBonusDataModel dataModel = new ShopBonusDataModel();
            ShopBonusModel model = new ShopBonusModel(this._bonusService.Get(id));

            dataModel.GrantId = grantid;
            dataModel.ShareHref = host + "/m-weixin/shopbonus/index/" + grantid.ToString();
            dataModel.HeadImg = wxhead;
            //dataModel.HeadImg = Himall.Core.HimallIO.GetImagePath(dataModel.HeadImg);
            dataModel.ShopAddress = GetShopAddress(model.ShopId);
            dataModel.Price = price;
            dataModel.OpenId = openId;
            dataModel.ShopName = Application.ShopApplication.GetShopName(model.ShopId);
            ViewBag.DataModel = dataModel;
            model.ShareImg = HimallIO.GetImagePath(model.ShareImg);
            if (!string.IsNullOrWhiteSpace(model.ShareImg))
            {
                if (model.ShareImg.Substring(0, 4) != "http")
                {
                    model.ShareImg = host + model.ShareImg;
                }
            }
            model.ReceiveId = rid;

            #region 同步微信前信息准备
            if (model.SynchronizeCard == true && this.PlatformType == PlatformType.WeiXin)
            {

src/Himall.Web/Areas/SellerAdmin/Views/ShopBonus/BuyService.cshtml
@model Himall.Web.Areas.SellerAdmin.Models.ShopBonusBuyServiceViewModel
@{
    ViewBag.Title = "购买随机红包服务";
}

<script src="~/Scripts/v.js"></script>
<div class="container">
    <ul class="nav nav-tabs-custom clearfix">

        <li class=""><a href="@Url.Action("Management")">管理</a></li>
        @if( Model.Market != null && Model.Market.MarketServiceRecordInfo.Max( a => a.EndTime ) >= DateTime.Now.Date )
        {
            <li class=""><a href="#" onclick="isad( '@Url.Action("Add")' )">添加代金红包</a></li>
        }
        <li class="active"><a>购买服务</a></li>
    </ul>
    @if (Model.IsNo)
    {
          <form id="form1" action="@Url.Action("BuyService")" method="post">
        <div class="form-horizontal">
            <div class="form-group">
                @if (null != Model.EndDate)
                {
                    <label class="col-sm-2 control-label" for="">服务到期时间：</label>
                    <span class="pl20 lh30">@Model.EndDate</span>
                    <span class="help-default pl20 lh30">每月您需要支付<span class="red"> @Model.Price.ToString("f2") </span> 元，相关费用会在店铺的账期结算中扣除</span>
                }
                else
                {
                    <label class="col-sm-2 control-label" for=""></label>
                    <span class="red pl20">您未购买代金红包服务</span>
                    <span class="help-default pl20 lh30">每月您需要支付 @Model.Price.ToString("f2") 元</span>
                }
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label" for="">购买数量：</label>
                <div class="col-sm-10"><input class="form-control input-sm input-int-num" type="text" id="range" name="month" data-price="@Model.Price.ToString("f2")" style="width:105px; display:inline-block" /> &nbsp; 月</div>
            </div>
            <div class="form-group">
                <input type="submit" style="display:none" id="submit" />
                <div class="col-sm-3 col-sm-offset-2"><button id="btnSave" type="button" class="btn btn-primary btn-sm color-f">确认购买</button></div>
            </div>
        </div>
    </form>
    }
    else
    { 
        <div class="form-horizontal">
			<div class="form-group">
				<p class="apply-primary"><span class="glyphicon glyphicon-info-sign"></span>平台未开启随机红包功能</p>
			</div>
		</div>
    }
  
</div>

<script type="text/javascript">
    function isad( href )
    {
        $.post( "/SellerAdmin/ShopBonus/isadd", {}, function ( data )
        {
            if ( data )
            {
                location.href = href;
            }
            else
            {
                $.dialog.tips( '一个时间段只能新增一个随机红包！' );
            }
        } );
    }

    $( function ()
    {
        $( "#range" ).focus();

        $('#btnSave').click(function () {
            var month = $("#range").val();
            var price = $("#range").data("price");
            if (month.length>0 && month <= 12) {
                $.dialog.confirm('您确定花费' + month * price + '元购买' + month + '个月代金红包服务吗？', function () {
                    $('#submit').click();
                });
            }
        })
    } );
    var a = v( {
        form: 'form1',
        ajaxSubmit: true,
        beforeSubmit: function ()
        {
            loadingobj = showLoading();
        },
        afterSubmit: function ( data )
        {// 表单提交成功回调
            loadingobj.close();
            var d = data;
            if ( d.success )
            {
                $.dialog.succeedTips( "提交成功！", function ()
                {
                    window.location.reload();
                }, 0.3 );
            } else
            {
                $.dialog.alert(data.msg, '', 3);
            }
        }
    } );
    a.add(
        {
            target: 'range',
            empty: true,
            ruleType: 'uint&&(value>0)&&(value<=12)',// v.js规则验证
            error: '只能为数字，且只能是1到12之间的整数!'
        } );
</script>

src/Himall.Web/Areas/SellerAdmin/Views/ShopBonus/Edit.cshtml
@model Himall.Web.Areas.SellerAdmin.Models.ShopBonusModel
@{
    string WXColorValue = "";
    if (Model.CardColor != null)
    {
        WXColorValue = Himall.Model.WXCardLogInfo.WXCardColors[Model.CardColor].ToString();
    }
}
<script src="~/Scripts/jquery.himallUpload.js"></script>
<link rel="stylesheet" type="text/css" href="~/Content/bootstrap-datetimepicker.min.css">
<script type="text/javascript" src="~/Scripts/bootstrap-datetimepicker.js"></script>
<script type="text/javascript" src="~/Scripts/bootstrap-datetimepicker.zh-CN.js"></script>
<style>
    input[type="radio"] { margin-top: 9px; }

    .w50 { width: 50px; }
</style>

<div class="container">
    <ul class="breadcrumb clearfix">

        <li><a href="/SellerAdmin/ShopBonus/Management">代金红包管理</a></li>
        <li class="active"><a>编辑代金红包</a></li>
    </ul>

    @using (Html.BeginForm("EditData", "ShopBonus", new { Area = "SellerAdmin" }, FormMethod.Post, new { id = "BonusForm", @class = "form-horizontal" }))
    {
        @Html.HiddenFor(p => p.Id);

        <div class="form-group">
            <label for="" class="col-sm-2 control-label">活动名称：</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(p => p.Name, new { @class = "form-control input-sm", @maxlength = "20" })
            </div>
        </div>

        <div class="form-group">
            <label for="" class="col-sm-2 control-label">红包个数：</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(p => p.Count, new { @class = "form-control input-sm", @readonly = "true" })
            </div>
            <div class="col-sm-6">
                <p class="help-default">1-1000,会员获得红包并分享出去后可被领取到的总个数</p>
            </div>
        </div>

        <div class="form-group">
            <label for="" class="col-sm-2 control-label">随机范围：</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(p => p.RandomAmountStart, new { @class = "w50", @onkeypress = "return (/[\\d.]/.test(String.fromCharCode(event.which?event.which:window.event.keyCode)))", @disabled = "true" }) 至
                @Html.TextBoxFor(p => p.RandomAmountEnd, new { @class = "w50", @onkeypress = "return (/[\\d.]/.test(String.fromCharCode(event.which?event.which:window.event.keyCode)))", @disabled = "true" }) 元
            </div>
        </div>

        <div class="form-group">
            <label for="" class="col-sm-2 control-label">使用条件：</label>
            <div class="col-sm-3">
                @if (Model.UseState == Himall.Model.ShopBonusInfo.UseStateType.None)
                {
                    @Html.RadioButtonFor(p => p.UseState, (int)Himall.Model.BonusInfo.BonusType.Activity, new { @name = "UseState", @id = "rdi1", @disabled = "true" })
                    <label for="rdi1">满</label>
                    @Html.TextBoxFor(p => p.UsrStatePrice, new { @class = "w50", @onkeypress = "return (/[\\d.]/.test(String.fromCharCode(event.which?event.which:window.event.keyCode)))", @disabled = "true" }) <br />
                    @Html.RadioButtonFor(p => p.UseState, (int)Himall.Model.BonusInfo.BonusType.Attention, new { @name = "UseState", @id = "rdi2", @disabled = "true", @Checked = "checked" })
                    <label for="rdi1">无限制</label>
                }
                else
                {

                    @Html.RadioButtonFor(p => p.UseState, (int)Himall.Model.BonusInfo.BonusType.Activity, new { @name = "UseState", @id = "rdi1", @disabled = "true", @Checked = "checked" })
                    <label for="rdi1">满</label>
                    @Html.TextBoxFor(p => p.UsrStatePrice, new { @class = "w50", @onkeypress = "return (/[\\d.]/.test(String.fromCharCode(event.which?event.which:window.event.keyCode)))", @disabled = "true" }) <br />
                    @Html.RadioButtonFor(p => p.UseState, (int)Himall.Model.BonusInfo.BonusType.Attention, new { @name = "UseState", @id = "rdi2", @disabled = "true" })
                    <label for="rdi1">无限制</label>
                }

            </div>
        </div>

        <div class="form-group">
            <label for="" class="col-sm-2 control-label">发放方式：</label>
            <div class="col-sm-3">
                <label for="rdi1">购物满</label>
                @Html.TextBoxFor(p => p.GrantPrice, new { @class = "w50", @onkeypress = "return (/[\\d.]/.test(String.fromCharCode(event.which?event.which:window.event.keyCode)))" }) 元
            </div>
            <div class="col-sm-6">
                <p class="help-default">订单实付金额达到设定的值可获得，0元代表任何付完款的订单均可获得红包</p>
            </div>
        </div>

        <div class="form-group">
            <label for="" class="col-sm-2 control-label">活动开始时间：</label>
            <div class="col-sm-3">
                <input type="text" class="form-control input-sm end_datetime" name="DateStart" id="DateStart" value="@Model.DateStartStr" />
            </div>
        </div>

        <div class="form-group">
            <label for="" class="col-sm-2 control-label">活动截止时间：</label>
            <div class="col-sm-3">
                <input type="text" class="form-control input-sm end_datetime" name="DateEnd" id="DateEnd" value="@Model.DateEndStr" />
            </div>
            <div class="col-sm-5">
                <p class="help-default">活动时间内才能够发放红包</p>
            </div>
        </div>

        <div class="form-group">
            <label for="" class="col-sm-2 control-label">红包有效期限：</label>
            <div class="col-sm-3">
                <input type="text" readonly class="form-control input-sm" name="BonusDateStart" id="BonusDateStart" value="@Model.BonusDateStartStr" />
                <label for="rdi1">至</label>
                <input type="text" readonly class="form-control input-sm " name="BonusDateEnd" id="BonusDateEnd" value="@Model.BonusDateEndStr" />
            </div>
        </div>

        <div class="form-group">
            <label for="" class="col-sm-2 control-label">分享标题：</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(p => p.ShareTitle, new { @class = "form-control input-sm", @maxlength = "20" })
            </div>
            <div class="col-sm-6">
                <p class="help-default">红包被分享或发送出去后链接的名称，如：火拼双11，百万礼券疯狂抢</p>
            </div>
        </div>

        <div class="form-group">
            <label for="" class="col-sm-2 control-label">分享详情：</label>
            <div class="col-sm-3">
                @Html.TextAreaFor(p => p.ShareDetail, new { @class = "form-control input-sm", @maxlength = "60" })
            </div>
            <div class="col-sm-6">
                <p class="help-default">红包被发送出去后链接的详情描述</p>
            </div>
        </div>

        <div class="form-group">
            <label for="" class="col-sm-2 control-label">分享图标：</label>
            <div class="col-sm-3">
                <div id="upload-img" class="form-group upload-img"></div>
            </div>
            <div class="col-sm-5">
                <p class="help-default">活动被分享出去的链接图标<label class="pic-upload-suggest"></label></p>
            </div>
        </div>

        <div class="form-group">
            <label for="" class="col-sm-2 control-label">同步发布至：</label>
            <div class="col-sm-3">
                @Html.CheckBoxFor(p => p.SynchronizeCard, new { @class = "input-sm", @disabled = "true" })
                <label for="rdi1">微信卡包</label>
            </div>
            <div class="col-sm-6">
                <p class="help-default">如您的微信公众号没有开通卡券权限，将由平台公众号代发券。同步至微信卡包后，需等待微信审核通过，才能领取；</p>
            </div>
        </div>

        <div class="form-group">
            <label for="" class="col-sm-2 control-label">卡券颜色：</label>
            <div class="col-sm-3">
                <input type="text" style="background:@WXColorValue;color:#fff;" class="form-control input-sm" value="@Model.CardColor" />
                @*@Html.TextBoxFor( p => p.CardColor , new { @class = "form-control input-sm" , @maxlength = "30" , @disabled = "true" } )>*@
            </div>
        </div>

        <div class="form-group">
            <label for="" class="col-sm-2 control-label">卡券标题：</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(p => p.CardTitle, new { @class = "form-control input-sm", @maxlength = "30", @disabled = "true" })
            </div>
            <div class="col-sm-6">
                <p class="help-default">建议填写代金券“减免金额”及自定义内容，描述卡券提供的具体优惠。例如：HiMall 100元代金券;字数上限为9个汉字</p>
            </div>
        </div>

        <div class="form-group">
            <label for="" class="col-sm-2 control-label">副标题 (非必填)：</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(p => p.CardSubtitle, new { @class = "form-control input-sm", @maxlength = "18", @disabled = "true" })
            </div>
            <div class="col-sm-6">
                <p class="help-default">字数上限为18</p>
            </div>
        </div>


        <div class="form-group">
            <label for="" class="col-sm-2 control-label">每个订单每人限领：</label>
            <div class="col-sm-3">
                <label for="rdi1">1次</label>
            </div>
        </div>

        <div class="form-group">
            <label for="" class="col-sm-2 control-label">使用范围：</label>
            <div class="col-sm-3">
                <label for="rdi1">全店通用</label>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="button" id="subCate" class="btn btn-primary">保 存</button>
            </div>
        </div>
    }
</div>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

<script type="text/javascript">
    $( function ()
    {
        $( "#subCate" ).click( function ()
        {
            if ( check() )
            {
                document.getElementById( "BonusForm" ).submit();
            }
        } );

        $( "#upload-img" ).himallUpload( {
            title: '',
            imageDescript: '100*100图片',
            imgFieldName: "ShareImg",
            displayImgSrc: "@(Himall.Core.HimallIO.GetImagePath(Model.ShareImg))",
            dataWidth: 10
        } );

        $( ".start_datetime" ).datetimepicker( {
            language: 'zh-CN',
            format: 'yyyy-mm-dd',
            autoclose: true,
            weekStart: 1,
            minView: 2
        } );
        $( ".end_datetime" ).datetimepicker( {
            language: 'zh-CN',
            format: 'yyyy-mm-dd',
            autoclose: true,
            weekStart: 1,
            minView: 2
        } );

        //$( '.start_datetime' ).on( 'changeDate', function ()
        //{
        //    if ( $( ".end_datetime" ).val() )
        //    {
        //        if ( $( ".start_datetime" ).val() > $( ".end_datetime" ).val() )
        //        {
        //            $( '.end_datetime' ).val( $( ".start_datetime" ).val() );
        //        }
        //    }

        //    $( '.end_datetime' ).datetimepicker( 'setStartDate', $( ".start_datetime" ).val() );
        //} );

    } )

    function check()
    {
        if ( $.trim( $( "#Name" ).val() ) == "" )
        {
            $.dialog.tips( '活动名称不能为空！' );
            return false;
        }

        var grantpricr = $.trim( $( "#GrantPrice" ).val() );
        if ( grantpricr == "" || parseFloat( grantpricr ) < 0 )
        {
            $.dialog.tips( '发放条件不能小于0！' );
            return false;
        }

        var bcount = $("#Count").val();
            bcount = parseInt(bcount);
        if (isNaN(bcount)) {
            $.dialog.tips('红包个数请输入数字！');
            return false;
        }
        if (bcount < 1 || bcount>1000) {
            $.dialog.tips('红包个数请控制在1-1000个！');
            return false;
        }
        $("#Count").val(bcount);

        if ( $.trim( $( "#DateStart" ).val() ) == '' )
        {
            $.dialog.tips( '活动开始日期必填！' );
            return false;
        }
        if ( $.trim( $( "#DateEnd" ).val() ) == '' )
        {
            $.dialog.tips( '活动结束日期必填！' );
            return false;
        }


        if ( $.trim( $( "input[name=ShareImg]" ).val() ) == '' )
        {
            $.dialog.tips( '请上传图片！' );
            return false;
        }

        return true;
    }
</script>