src/Himall.Web/Areas/Admin/Controllers/LimitTimeBuyController.cs
using Himall.Web.Framework;
using System;
using System.Collections.Generic;
using System.Linq;
using Himall.Core;
using System.Web;
using System.Web.Mvc;

using Himall.DTO.QueryModel;
using Himall.Model;
using Himall.IServices;
using Himall.Web.Areas.Admin.Models;
using Himall.Web.Models;
using Himall.Core.Helper;
using System.IO;
using Himall.CommonModel;
using Himall.DTO;
using Himall.Application;

namespace Himall.Web.Areas.Admin.Controllers
{
    [MarketingAuthorization]
    public class LimitTimeBuyController : BaseAdminController
    {
        private ILimitTimeBuyService _iLimitTimeBuyService;
        private IMarketService _iMarketService;
        private ISlideAdsService _iSlideAdsService;

        public LimitTimeBuyController(ILimitTimeBuyService iLimitTimeBuyService, IMarketService iMarketService, ISlideAdsService iSlideAdsService)
        {
            _iLimitTimeBuyService = iLimitTimeBuyService;
            _iMarketService = iMarketService;
            _iSlideAdsService = iSlideAdsService;
        }

        #region 活动列表

        // GET: Admin/LimitTimeBuy
        public ActionResult Management()
        {
            return View();
        }

        public ActionResult Audit(long id)
        {
            var result = _iLimitTimeBuyService.Get(id);
            ViewBag.IsAudit = true;
            return View(result);
        }

        public ActionResult Detail(long id)
        {
            var result = _iLimitTimeBuyService.Get(id);
            ViewBag.IsAudit = false;
            return View(result);
        }

        [HttpPost]
        [UnAuthorize]
        public JsonResult List(int? status, int page, int rows, string shopName, string title, string productName = "")
        {
            if (status == null)
            {
                status = 0;
            }

            QueryPageModel<FlashSaleInfo> result = _iLimitTimeBuyService.GetAll((int)status, shopName, title, page, rows, productName);
            IEnumerable<FlashSaleModel> market = result.Models.ToArray().Select(item =>

           {
               var m = new FlashSaleModel();
               m.Id = item.Id;
               m.Title = item.Title;
               m.BeginDate = item.BeginDate.ToString("yyyy-MM-dd");
               m.EndDate = item.EndDate.ToString("yyyy-MM-dd");
               m.ShopName = item.Himall_Shops.ShopName;
               m.ProductName = item.Himall_Products.ProductName;
               m.ProductId = item.ProductId;
               //StatusStr = item.EndDate < DateTime.Now ?FlashSaleInfo.FlashSaleStatus.Ended.ToDescription() : item.Status.ToDescription() ,
               m.StatusStr = item.Status.ToDescription();
               if (item.Status != FlashSaleInfo.FlashSaleStatus.WaitForAuditing && item.Status != FlashSaleInfo.FlashSaleStatus.AuditFailed && item.BeginDate > DateTime.Now && item.EndDate < DateTime.Now)
               {
                   m.StatusStr = "进行中";
               }
               else if (item.Status != FlashSaleInfo.FlashSaleStatus.WaitForAuditing && item.Status != FlashSaleInfo.FlashSaleStatus.AuditFailed && item.BeginDate > DateTime.Now)
               {
                   m.StatusStr = "未开始";
               }
               m.SaleCount = item.SaleCount;
               m.MinPrice = item.MinPrice;
               m.MarketPrice = item.Himall_Products.MarketPrice;
               m.ProductImg = Himall.Core.HimallIO.GetProductSizeImage(item.Himall_Products.ImagePath, 1, (int)ImageSize.Size_350);
               return m;
           });




            DataGridModel<FlashSaleModel> dataGrid = new DataGridModel<FlashSaleModel>() { rows = market, total = result.Total };
            return Json(dataGrid);
        }


        /// <summary>
        /// 审核
        /// </summary>
        /// <param name="Id"></param>
        /// <param name="auditState">审核状态</param>
        /// <param name="message">理由</param>
        /// <returns></returns>
        [UnAuthorize]
        [OperationLog(Message = "审核商品状态")]
        [HttpPost]
        public JsonResult AuditItem(long id)
        {

            Result result = new Result();
            try
            {
                _iLimitTimeBuyService.Pass(id);
                Cache.Remove(CacheKeyCollection.CACHE_LIMITPRODUCTS);
                result.success = true;
                result.msg = "审核成功！";
            }
            catch (HimallException ex)
            {
                result.msg = ex.Message;
            }
            catch (Exception ex)
            {
                Log.Error("审核出错", ex);
                result.msg = "审核出错！";
            }
            return Json(result);
        }

        /// <summary>
        /// 拒绝
        /// </summary>
        [UnAuthorize]
        [OperationLog(Message = "拒绝商品状态")]
        [HttpPost]
        public JsonResult RefuseItem(long id)
        {

            Result result = new Result();
            try
            {
                _iLimitTimeBuyService.Refuse(id);
                result.success = true;
                result.msg = "成功拒绝！";
            }
            catch (HimallException ex)
            {
                result.msg = ex.Message;
            }
            catch (Exception ex)
            {
                Log.Error("拒绝出错", ex);
                result.msg = "拒绝出错！";
            }
            return Json(result);
        }

        [HttpPost]
        [UnAuthorize]
        public JsonResult CancelItem(long id)
        {
            Result result = new Result();
            try
            {
                _iLimitTimeBuyService.Cancel(id);
                result.success = true;
                result.msg = "取消成功！";
            }
            catch (HimallException ex)
            {
                result.msg = ex.Message;
            }
            catch (Exception ex)
            {
                Log.Error("取消出错", ex);
                result.msg = "取消出错！";
            }
            return Json(result);
        }



        public ActionResult SetSlide()
        {
            return View();
        }

        #endregion

        #region 轮播图

        public JsonResult GetSlideJson()
        {
            var data = _iSlideAdsService.GetSlidAds(0, SlideAdInfo.SlideAdType.PlatformLimitTime);
            IEnumerable<HandSlideModel> slide = data.ToArray().Select(item => new HandSlideModel()
            {
                Id = item.Id,
                Pic = Core.HimallIO.GetImagePath(item.ImageUrl),
                URL = item.Url,
                Index = item.DisplaySequence
            });

            DataGridModel<HandSlideModel> dataGrid = new DataGridModel<HandSlideModel>() { rows = slide, total = slide.Count() };
            return Json(dataGrid);
        }

        [HttpPost]
        [UnAuthorize]
        public JsonResult AddSlideAd(string pic, string url)
        {
            var slide = new SlideAdInfo()
            {
                ImageUrl = pic,
                Url = url,
                ShopId = 0,
                DisplaySequence = 0,
                TypeId = SlideAdInfo.SlideAdType.PlatformLimitTime
            };
            if (!string.IsNullOrWhiteSpace(pic))
            {
                if (pic.Contains("/temp/"))
                {
                    string source = pic.Substring(pic.LastIndexOf("/temp/"));
                    string dest = @"/Storage/Plat/ImageAd/";
                    pic = dest + Path.GetFileName(pic);
                    Core.HimallIO.CopyFile(source, pic, true);
                }
                else if (pic.Contains("/Storage/"))
                {
                    pic = pic.Substring(pic.LastIndexOf("/Storage/"));
                }

                slide.ImageUrl = pic;
            }
            _iSlideAdsService.AddSlidAd(slide);
            return Json(new Result { success = true }, JsonRequestBehavior.AllowGet);
        }

        [UnAuthorize]
        public JsonResult DeleteSlide(long Id)
        {
            _iSlideAdsService.DeleteSlidAd(0, Id);
            return Json(new Result { success = true }, JsonRequestBehavior.AllowGet);
        }

        [UnAuthorize]
        public JsonResult EditSlideAd(long id, string pic, string url)
        {
            var slide = _iSlideAdsService.GetSlidAd(0, id);

            if (!string.IsNullOrWhiteSpace(pic) && (!slide.ImageUrl.Equals(pic)))
            {
                if (pic.Contains("/temp/"))
                {
                    string source = pic.Substring(pic.LastIndexOf("/temp/"));
                    string dest = @"/Storage/Plat/ImageAd/";
                    pic = dest + Path.GetFileName(pic);
                    Core.HimallIO.CopyFile(source, pic, true);
                }
                else if (pic.Contains("/Storage/"))
                {
                    pic = pic.Substring(pic.LastIndexOf("/Storage/"));
                }
            }

            _iSlideAdsService.UpdateSlidAd(new SlideAdInfo
            {
                Id = id,
                ImageUrl = pic,
                Url = url
            });
            return Json(new Result { success = true }, JsonRequestBehavior.AllowGet);
        }

        [UnAuthorize]
        [HttpPost]
        public ActionResult AdjustSlideIndex(long id, int direction)
        {
            _iSlideAdsService.AdjustSlidAdIndex(0, id, direction == 1, SlideAdInfo.SlideAdType.PlatformLimitTime);
            return Json(new Result { success = true }, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region 服务购买列表

        public ActionResult BoughtList()
        {
            return View();
        }

        [UnAuthorize]
        public JsonResult GetBoughtJson(string shopName, int page, int rows)
        {
            var queryModel = new MarketBoughtQuery()
            {
                PageSize = rows,
                PageNo = page,
                ShopName = shopName,
                MarketType = MarketType.LimitTimeBuy
            };

src/Himall.Web/Areas/SellerAdmin/Views/LimitTimeBuy/Add.cshtml
@{
    ViewBag.Title = "Add";
}
<link rel="stylesheet" type="text/css" href="~/Content/bootstrap-datetimepicker.min.css">
<script type="text/javascript" src="~/Scripts/bootstrap-datetimepicker.js"></script>
<script type="text/javascript" src="~/Scripts/bootstrap-datetimepicker.zh-CN.js"></script>
<script src="~/Areas/SellerAdmin/Scripts/LimitTimeBuyAdd.js"></script>
<div class="container">
    <ul class="nav nav-tabs-custom clearfix">
        
        <li><a href="./Management">活动管理</a></li>
        <li class="active"><a>新增限时购</a></li>
        <li class=""><a href="./BuyService">购买服务</a></li>
        
    </ul>

    <div class="form-horizontal">
        <div class="form-group">
            <label class="col-sm-2 control-label" for="">活动标题：</label>
            <div class="col-sm-3"><input id="txtTitle" type="text" value="限时折扣" class="form-control input-sm" maxlength="5" /></div>
            <div class="col-sm-7"><span class="help-default">活动标题是商家对限时折扣活动的别名操作，请使用例如“新品打折”、“月末折扣”类短语表现，限5个字；非必填选项，默认显示“限时折扣”字样。</span></div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label" for=""><b style="color:red;">*</b>活动商品：</label>
            <div class="col-sm-3"><input id="txtProductName" type="text" class="form-control input-sm" readonly="readonly" /></div>
            <div class="col-sm-3"><a class="btn btn-primary btn-sm" id="SelectProduct"><span class="glyphicon glyphicon-plus-sign"></span>&nbsp; 选择商品</a></div>
            <input type="hidden" id="txtProductId" name="ProductId" value="" />
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label" for=""><b style="color:red;">*</b>商品详情：</label>
            <div class="col-sm-9">
                <table id="tbl" class="table table-bordered">
                    <thead>
                        <tr>
                            <td>主商品</td>
                            <td>规格</td>
                            <td>原价</td>
                            <td>限时价</td>
                            <td>库存</td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr><td colspan="5" align="center">请先选择商品</td></tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label" for=""><b style="color:red;">*</b>活动分类：</label>
            <div class="col-sm-3">@Html.GenerateSelectHtml( ( List<SelectListItem> )ViewBag.Cate , "txtCategoryName" )</div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label" for=""><b style="color:red;">*</b>开始时间：</label>
            <div class="col-sm-3"><input id="txtBeginDate" type="text" class="form-control input-sm start_datetime" /></div>
            <div class="col-sm-5"><span class="help-default">建议开始时间晚于当前时间，用于预留审核时间及活动预热时间</span></div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label" for=""><b style="color:red;">*</b>结束时间：</label>
            <div class="col-sm-3"><input id="txtEndDate" type="text" class="form-control input-sm end_datetime" /></div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label" for=""><b style="color:red;">*</b>购买限制：</label>
            <div class="col-sm-3"><input id="txtCount" type="text" maxlength="5" class="form-control input-sm input-int-num" /></div>
            <div class="col-sm-5"><span class="help-default">单个ID最多购买数量</span></div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="button" id="submit" class="btn btn-primary">保存</button>
            </div>
        </div>
    </div>
    <input type="hidden" value="@Url.Action("Management")" id="UAm" />
    <input type="hidden" value="@DateTime.Now.ToString("yyyy-MM-dd HH:mm"):00" id="DNT0" />
    <input type="hidden" value="@ViewBag.EndTime" id="VBET" />
    <script src="~/Scripts/jquery.himallLinkage.nocreate.js"></script>
    <script src="~/Scripts/jquery.hiMallDatagrid.js"></script>
    <script src="~/Scripts/jquery.productSelector.js"></script>

src/Himall.Web/Areas/SellerAdmin/Views/LimitTimeBuy/AddLimitItem.cshtml
@model Himall.Web.Areas.SellerAdmin.Models.LimitTimeMarketModel

@{
    ViewBag.Title = "AddLimitItem";
}


<link rel="stylesheet" type="text/css" href="~/Content/bootstrap-datetimepicker.min.css">
<script type="text/javascript" src="~/Scripts/bootstrap-datetimepicker.js"></script>
<script type="text/javascript" src="~/Scripts/bootstrap-datetimepicker.zh-CN.js"></script>

<script src="~/Scripts/v.js"></script>
<script src="~/Areas/SellerAdmin/Scripts/LimitTimeBuyAddLimitItem.js"></script>
<input type="hidden" value="@DateTime.Now.ToString("yyyy-MM-dd")" id="DNT1" />
<input type="hidden" value="@ViewBag.EndTime" id="VBET" />
<div class="container">
    <ul class="nav nav-tabs-custom clearfix">

        <li><a href="./Management">活动管理</a></li>
        <li class="active"><a>新增限时购</a></li>
        <li class=""><a href="./BuyService">购买服务</a></li>

    </ul>
    @using (Html.BeginForm("AddLimitItem", "LimitTimeBuy", FormMethod.Post, new { id = "form1" }))
    {
        <div class="form-horizontal">
            <div class="form-group">
                <label class="col-sm-2 control-label" for=""><b style="color:red;">*</b>活动标题：</label>
                <div class="col-sm-3">@Html.EditorFor(item => item.Title, new { htmlAttributes = new { @class = "form-control input-sm" } }) </div>
                <div class="col-sm-5"><span class="help-default">活动标题是商家对限时折扣活动的别名.</span></div>
            </div>

            <div class="form-group">
                <label class="col-sm-2 control-label" for=""><b style="color:red;">*</b>活动商品：</label>
                <div class="col-sm-3">@Html.EditorFor(item => item.ProductName, new { htmlAttributes = new { @class = "form-control input-sm", @readonly = "readonly" } })</div>
                <div class="col-sm-3"><a class="btn btn-primary btn-sm" id="SelectProduct"><span class="glyphicon glyphicon-plus-sign"></span>&nbsp; 选择商品</a></div>
                <input type="hidden" id="ProductId" name="ProductId" value="" />
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label" for=""><b style="color:red;">*</b>原价格：</label>
                <div class="col-sm-3">@Html.EditorFor(item => item.ProductPrice, new { htmlAttributes = new { @class = "form-control input-sm", @readonly = "readonly" } })</div>
                <div class="col-sm-5"><span class="help-default">选择商品之后，会自动填充.</span></div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label" for=""><b style="color:red;">*</b>限时购价格：</label>
                <div class="col-sm-3">@Html.EditorFor(item => item.Price, new { htmlAttributes = new { @class = "form-control input-sm" } })</div>
                <div class="col-sm-5"><span class="help-default">限时购价格必须低于原价格；在活动期内，不能修改商品价格.</span></div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label" for=""><b style="color:red;">*</b>活动分类：</label>
                <div class="col-sm-3">@Html.GenerateSelectHtml((List<SelectListItem>)ViewBag.Cate, "CategoryName")</div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label" for=""><b style="color:red;">*</b>开始时间：</label>
                <div class="col-sm-3">@Html.EditorFor(item => item.StartTime, new { htmlAttributes = new { @class = "form-control input-sm start_datetime" } })</div>
                <div class="col-sm-5"><span class="help-default">开始时间最好晚于当前时间+默认的2天审核时间.</span></div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label" for=""><b style="color:red;">*</b>结束时间：</label>
                <div class="col-sm-3">@Html.EditorFor(item => item.EndTime, new { htmlAttributes = new { @class = "form-control input-sm end_datetime"} })</div>
                <div class="col-sm-5"><span class="help-default">结束时间必须晚于开始时间.</span></div>
            </div>
            @*@if (Model != null)
                {
                    <div class="form-group">
                        <label class="col-sm-2 control-label" for=""><b style="color:red;">*</b>库存数量：</label>
                        <div class="col-sm-3">@Html.EditorFor(item => item.Stock, new { htmlAttributes = new { @class = "form-control input-sm", @readonly = "readonly" } }) 件</div>
                    </div>
                }
                else
                {
                <div class="form-group">
                    <label class="col-sm-2 control-label" for=""><b style="color:red;">*</b>库存数量：</label>
                    <div class="col-sm-3">@Html.EditorFor(item => item.Stock, new { htmlAttributes = new { @class = "form-control input-sm" } }) 件</div>
                </div>
                }*@
            @Html.HiddenFor(item => item.Stock, new { htmlAttributes = new { @class = "form-control input-sm" } })
            <div class="form-group">
                <label class="col-sm-2 control-label" for=""><b style="color:red;">*</b>购买限制：</label>
                <div class="col-sm-3">@Html.EditorFor(item => item.MaxSaleCount, new { htmlAttributes = new { @class = "form-control input-sm" } })</div>
                <div class="col-sm-5"><span class="help-default">单个人最多购买数量.</span></div>
            </div>
            <div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
                	<button type="submit" class="btn btn-primary">保存</button><label class="label-inline" for=""><a href="./Management">返回</a></label>
				</div>
            </div>
        </div>
    }
</div>
<input type="hidden" value="@Url.Action("Management")" id="UAmag"/>
<script src="~/Scripts/jquery.himallLinkage.nocreate.js"></script>
<script src="~/Scripts/jquery.hiMallDatagrid.js"></script>
<script src="~/Scripts/jquery.productSelector.js"></script>

src/Himall.Web/Areas/SellerAdmin/Views/LimitTimeBuy/EditLimitItem.cshtml
@model Himall.Web.Areas.SellerAdmin.Models.LimitTimeMarketModel

@{
    ViewBag.Title = "EditLimitItem";
}


<script src="~/Scripts/jquery.himallLinkage.nocreate.js"></script>
<script src="~/Scripts/jquery.hiMallDatagrid.js"></script>
<script src="~/Scripts/jquery.productSelector.js"></script>
<script src="~/Scripts/v.js"></script>
<link rel="stylesheet" type="text/css" href="~/Content/bootstrap-datetimepicker.min.css">
<script type="text/javascript" src="~/Scripts/bootstrap-datetimepicker.js"></script>
<script type="text/javascript" src="~/Scripts/bootstrap-datetimepicker.zh-CN.js"></script>

<div class="container">
    <ul class="nav nav-tabs-custom clearfix">

        <li class="active"><a>活动管理</a></li>
        <li class=""><a href="../BuyService">购买服务</a></li>

    </ul>
    @using (Html.BeginForm("EditLimitItem", "LimitTimeBuy", FormMethod.Post, new { id = "form1" }))
    {
        <div class="custom-form">
            <div class="form-group">
                <label class="label-inline" for=""><b style="color:red;">*</b>活动标题：</label>
                @Html.EditorFor(item => item.Title, new { htmlAttributes = new { @class = "form-control input-sm" } })
                <span class="help-default">&nbsp;&nbsp;&nbsp;&nbsp;活动标题是商家对限时折扣活动的别名.</span>
            </div>
            <div class="form-group">
                <label class="label-inline" for=""><b style="color:red;">*</b>活动商品：</label>
                @Html.EditorFor(item => item.ProductName, new { htmlAttributes = new { @class = "form-control input-sm", @readonly = "readonly" } })
                <label class="label-inline" for=""><a class="btn btn-primary btn-ssm" id="SelectProduct"><span class="glyphicon glyphicon-plus-sign"></span>&nbsp; 选择商品</a></label>
               @Html.HiddenFor(item => item.ProductId, new { htmlAttributes = new { @class = "form-control input-sm" } })
            </div>
            <div class="form-group">
                <label class="label-inline" for=""><b style="color:red;">*</b>原价格：</label>
                @Html.EditorFor(item => item.ProductPrice, new { htmlAttributes = new { @class = "form-control input-sm", @readonly = "readonly" } }) 元
                <span class="help-default">&nbsp;&nbsp;&nbsp;&nbsp;选择商品之后，会自动填充.</span>
            </div>
            <div class="form-group">
                <label class="label-inline" for=""><b style="color:red;">*</b>限时购价格：</label>
                @Html.EditorFor(item => item.Price, new { htmlAttributes = new { @class = "form-control input-sm" } }) 元
                <span class="help-default">&nbsp;&nbsp;&nbsp;&nbsp;限时购价格必须低于原价格；在活动期内，不能修改商品价格.</span>
            </div>
            <div class="form-group">
                <label class="label-inline" for=""><b style="color:red;">*</b>活动分类：</label>
               @Html.GenerateSelectHtml((List<SelectListItem>)ViewBag.Cate, "CategoryName")
            </div>
            <div class="form-group">
                <label class="label-inline" for=""><b style="color:red;">*</b>开始时间：</label>
                @Html.EditorFor(item => item.StartTime, new { htmlAttributes = new { @class = "form-control input-sm start_datetime" } })
            </div>
            <div class="form-group">
                <label class="label-inline" for=""><b style="color:red;">*</b>结束时间：</label>
                @Html.EditorFor(item => item.EndTime, new { htmlAttributes = new { @class = "form-control input-sm end_datetime" } })
                <span class="help-default">&nbsp;&nbsp;&nbsp;&nbsp;结束时间必须晚于开始时间.</span>
            </div>

            @Html.HiddenFor(item => item.Stock, new { htmlAttributes = new { @class = "form-control input-sm" } })
            <div class="form-group">
                <label class="label-inline" for=""><b style="color:red;">*</b>购买限制：</label>
                @Html.EditorFor(item => item.MaxSaleCount, new { htmlAttributes = new { @class = "form-control input-sm" } }) 件
                <span class="help-default">&nbsp;&nbsp;&nbsp;&nbsp;单个人最多购买数量.</span>
            </div>
            <div class="form-group">
                <label class="label-inline" for=""><b style="color:red;">*</b>审核状态：</label>
                @(Model.AuditStatus)
                <span class="help-default">&nbsp;&nbsp;@(Model.CancelReson)</span>
            </div>
            <div class="dialog-form-btn">
                <label class="label-inline" for="">&nbsp;</label>
                <button type="submit" class="btn btn-primary">保存</button><label class="label-inline" for=""><a href="../Management">返回</a></label>
            </div>
        </div>
    }
</div>
@if (Model.AuditStatus=="待审核")
{ 
<script type="text/javascript">
    $(function () {
        $(".start_datetime").datetimepicker({
            format: 'yyyy-mm-dd',
            autoclose: true,
            weekStart: 1,
            language: 'zh-CN',
            minView: 2
        });
        $(".end_datetime").datetimepicker({
            format: 'yyyy-mm-dd',
            autoclose: true,
            weekStart: 1,
            language: 'zh-CN',
            minView: 2
        });
        $('.end_datetime').datetimepicker('setStartDate', $(".start_datetime").val());
        $('.start_datetime').datetimepicker('setStartDate',"@(DateTime.Now.ToString("yyyy-MM-dd"))");
        $('.start_datetime').datetimepicker('setEndDate', $(".end_datetime").val());
        $('.start_datetime').on('changeDate', function () {
            if ($(".end_datetime").val()) {
                if ($(".start_datetime").val() > $(".end_datetime").val()) {
                    $('.end_datetime').val($(".start_datetime").val());
                }
            }
            $('.end_datetime').datetimepicker('setStartDate', $(".start_datetime").val());
        });
        $('.end_datetime').on('changeDate', function () {
            $('.start_datetime').datetimepicker('setEndDate', $(".end_datetime").val());
        });
    });
</script>
}

<script>
    $(function () {
        $("#Title").focus();

        $("#SelectProduct").click(function () {
            $.productSelector.show(null, function (selectedProducts) {
                console.log(selectedProducts);
                $("#ProductId").val(selectedProducts[0].id);
                $("#ProductName").val(selectedProducts[0].name);
                $("#ProductPrice").val(selectedProducts[0].price);
            }, 'selleradmin', false);
        });
    });
        var a = v({
            form: 'form1',
            ajaxSubmit: true,
            beforeSubmit: function () {
                loadingobj = showLoading();
            },
            afterSubmit: function (data) {// 表单提交成功回调
                loadingobj.close();
                var d =data;
                if (d.success) {
                    $.dialog.succeedTips("保存成功！", function () {
                        window.location.href = "../Management";
                    });
                } else {
                    $.dialog.errorTips(d.msg, '', 1);
                }
            }
        });
        a.add(
             {
                 target: 'Title',
                 empty: true,
                 ruleType: 'required',// v.js规则验证
                 error: '请您填写活动标题'
             },
            {
                target: 'ProductName',
                empty: true,
                ruleType: 'required',// v.js规则验证
                error: '请您选择商品'
            }, {
                target: 'Price',
                empty: true,
                ruleType: 'money',// v.js规则验证
                fnRule: function () {
                    var a = $('#ProductPrice').val(),
                          b = $('#Price').val();
                    try{
                        a=parseFloat(a);
                    } catch (ex) {
                        a = 0;
                    }
                    try {
                        b = parseFloat(b);
                    } catch (ex) {
                        b = 0;
                    }
                    if (b >= a || b < 0 || a < 0) {
                        return false;
                    }
                },
                error: '只能为数字，  且大于0'
            }, {
                target: 'StartTime',
                ruleType: 'required',// v.js规则验证
                error: '请选择活动开始时间'
            }, {
                target: 'EndTime',
                ruleType: 'required',// v.js规则验证
                error: '请选择活动结束时间'
            }, {
                target: 'MaxSaleCount',
                empty: true,
                ruleType: 'uint&&(value>0)',// v.js规则验证
                error: '最大购买数只能为数字，  且大于0'
            });



</script>